# Generated by Django 3.2.12 on 2022-09-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_front', models.CharField(blank=True, max_length=1000, null=True)),
                ('img_back', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=1000, null=True)),
                ('oldprice', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('star', models.IntegerField(blank=True)),
                ('Reviews', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('long_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
