# Generated by Django 3.2.12 on 2022-09-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220917_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_back',
            field=models.CharField(blank=True, db_index=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_front',
            field=models.CharField(blank=True, db_index=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=10000, null=True),
        ),
    ]
