# Generated by Django 3.2.12 on 2022-09-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=10000, null=True),
        ),
    ]
