# Generated by Django 3.2.12 on 2022-09-25 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_request_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=10000, null=True)),
                ('action_type', models.CharField(blank=True, db_index=True, max_length=10000, null=True)),
                ('text', models.CharField(blank=True, db_index=True, max_length=10000, null=True)),
            ],
            options={
                'db_table': 'myaction',
            },
        ),
    ]
