version: "3.9"
   
services:
  web:
    build: .
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8001
      "
    volumes:
      - .:/code
    ports:
      - "8002:8001"
    environment:
      DATABASE_NAME: factory_datingdb
      DATABASE_USER: postgres
      DATABASE_PASS: code
      DATABASE_HOST: mermaidsparkdb
      DATABASE_PORT: 5432


    