version: "3.9"
   
services:
  web:
    build: .
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8001
      "
    volumes:
      - .:/code
    ports:
      - "80:8001"
    environment:
      DATABASE_NAME: mermaid_spark_db
      DATABASE_USER: postgres
      DATABASE_PASS: code
      DATABASE_HOST: 3.215.46.92
      DATABASE_PORT: 5432


    